# PerfectAPIClient document generator jazzy settings

copyright: Copyright 2017 Sven Tiigi
author: Sven Tiigi
github_url: https://github.com/SvenTiigi/PerfectAPIClient
xcodebuild_arguments: [-target, PerfectAPIClient]
module: PerfectAPIClient
clean: true
output: ./Documentation
min_acl: private