branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y openssl
  - sudo apt-get install -y libcurl4-openssl-dev
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR