branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - chmod +x /.travis/install-dependencies.sh

install:
  - ./.travis/install-dependencies.sh

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR