branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:0k53d-karl-f830m/openssl -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y openssl  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libssl-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libcurl4-openssl-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get build-dep curl -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ~/curl && cd ~/curl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://curl.haxx.se/download/curl-7.50.2.tar.bz2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvjf curl-7.50.2.tar.bz2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd curl-7.50.2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make && sudo make install && sudo ldconfig ; fi
  - curl --version
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR

after_success:
  - bash <(curl -s https://codecov.io/bash)