branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo add-apt-repository ppa:0k53d-karl-f830m/openssl -y;
          sudo apt-get -y update;
          sudo apt-get install -y openssl;
          sudo apt-get install -y libssl-dev;
          sudo apt-get install -y libcurl4-openssl-dev;
          sudo apt-get build-dep curl -y;
          mkdir curl;
          cd curl;
          wget http://curl.haxx.se/download/curl-7.50.2.tar.bz2;
          tar -xvjf curl-7.50.2.tar.bz2;
          cd curl-7.50.2;
          ./configure;
          make;
          sudo make install;
          sudo ldconfig;
          cd ../../;
    fi
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR

after_success:
  - bash <(curl -s https://codecov.io/bash)