branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - lsb_release -a
  - openssl version -a
  - sudo add-apt-repository ppa:0k53d-karl-f830m/openssl -y
  - sudo apt-get update -q
  - sudo apt-get install openssl -y
  - openssl version -a

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR